# Generated by Django 3.2.5 on 2021-07-29 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_villian'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Villian',
            new_name='Comedians',
        ),
    ]
